cd ..
currentpath = pwd;
cd fofb

pathlist = {...
    fullfile('fofb','control'), ...
    fullfile('fofb'), ...
    fullfile('libdsp'), ...
    fullfile('libunits'), ...
    };

for i = 1:length(pathlist)
    addpath(fullfile(currentpath, pathlist{i}))
end
