load lnls2.mat;

ss_matrices = struct('bpm_filter', [], ...
    'ps_dynamics', [], ...
    'vac_dynamics', [], ...
    'ctrl_algorithm', []);

simulate_fofb(config, disturbance_config, controller_config, ss_matrices);